### PR TITLE
Add Windows Recipe

### PR DESCRIPTION
**Pull request by patricksnape**
Just download the exe's rather than building from source since I don't think we ever need to link against them!

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please install `conda-smithy` and run `conda smithy rerender` here and commit those changes too? Also, could please run this in your own AppVeyor account as well just in case the queue is still too backed up here?

**Comment by jakirkham** [comment]
Thanks for re-rendering and setting up AppVeyor.

I assume that this is [your AppVeyor build](https://ci.appveyor.com/project/patricksnape/yasm-feedstock/build/1.0.1). The SHAs appear to be the same and it is passing.

Will go ahead and merge. Thanks for the addition, @patricksnape.

**Comment by jakirkham** [comment]
While you are correct that we shouldn't be linking against the assembler. We may want to investigate building from source for Windows in the future. Especially considering it does seem to have a [CMakeLists](https://github.com/yasm/yasm/blob/v1.2.0/CMakeLists.txt). Though maybe it is not that simple.

**Comment by jakirkham** [comment]
Released. :tada:

**Comment by patricksnape** [comment]
Yes you are write, and they also seem to ship a VC9 solution file, so it probably shouldn't be that hard actually.

**Comment by jakirkham** [comment]
Also, thanks for the 1.3.0 version bump. I had issues trying to get the new version to build locally on my Mac so had stuck with 1.2.0 when making the recipe.

However, it appears Travis didn't have any issues. So, it will be nice being able to use a newer version of the assembler going forward.

**Pull request merged**
